services:
  mysqldb:
    image: nkolonzilucky/mysqljhbtimezone
    ports:
      - 3307:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: nimda
      MYSQL_DATABASE: laundrySystem
      MYSQL_USER: lucky
      MYSQL_PASSWORD: qwerty
    command: 
      - mysqld
volumes:
  mysql-data:
